isomgr: fix clang compilation error
clang throws below compilation error. So, avoid comparison
between function pointers.

isomgr.h:46:3: error: ordered comparison of function pointers
 ('tegra_isomgr_renegotiate' (aka 'void (*)(void *, unsigned int)')
 and 'tegra_isomgr_renegotiate') [-Werror]

bug 1745660

Change-Id: I98c759345c5e14be97d79fef0a8ffe25408e2620
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1150403
(cherry picked from commit 95e2d74fdf6e24b1d4a78b68e9661a06e359c875)
Reviewed-on: http://git-master/r/1159917
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>