tegra: fuse: EXPORT tegra_get_chip_id and tegra_chip_get_revision
These two functions are being used by other drivers, which could be
select as loadable kernel modules. When compiling those modules, it
appears:

Building modules, stage 2.
MODPOST 58 modules
ERROR: "tegra_chip_get_revision" [drivers/crypto/tegra-se.ko] undefined!
ERROR: "tegra_get_chip_id" [drivers/crypto/tegra-se.ko] undefined!
make[3]: *** [__modpost] Error 1
make[2]: *** [modules] Error 2

So this patches just exports these two functions so that the linker
could find them for module compiling.

[ There are some other helper functions in this file being called by
  other drivers, however none of them (drivers) is selected for the
  topic of security and crypto. So this patch doesn't include those
  helper functions, but I thin that we probably will need them some
  day. -- Nicolin ]

Bug 1886707

Change-Id: Ia404b5038e39d7f99ba2a0eb87d70f605861f01d
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: http://git-master/r/1318306
Reviewed-by: svccoveritychecker <svccoveritychecker@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
(cherry picked from commit 037372a5c8b9ad7d0ad36df0e907302ac6a52dfa)