power: bq2471x: fix compilation error
Fix compilation error:
/**
bq2471x-charger.c: In function 'bq2471x_check_manufacturer':
bq2471x-charger.c:143:2: warning: passing argument 3 of 'bq2471x_read'
		from incompatible pointer type [enabled by default]
bq2471x-charger.c:98:12: note: expected 'unsigned int *' but argument is
		of type 'uint16_t *'
bq2471x-charger.c: In function 'bq2471x_show_chip_version':
bq2471x-charger.c:166:2: warning: passing argument 3 of 'bq2471x_read'
		from incompatible pointer type [enabled by default]
bq2471x-charger.c:98:12: note: expected 'unsigned int *' but argument is
		of type 'uint16_t *'
bq2471x-charger.c: In function 'bq2471x_hw_init':
bq2471x-charger.c:186:11: warning: unused variable 'val' [-Wunused-variable]
bq2471x-charger.c: In function 'bq2471x_probe':
bq2471x-charger.c:339:6: warning: passing argument 1 of 'dev_name'
		from incompatible pointer type [enabled by default]
In file included from linux/i2c.h:30:0,
                from bq2471x-charger.c:25:
device.h:741:27: note: expected 'const struct device *' but argument is
		of type 'struct device **'
bq2471x-charger.c:277:11: warning: unused variable 'val' [-Wunused-variable]
**/

Change-Id: I0f6710c4d7dcf5157b169fdf3245c8067003e650
Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Reviewed-on: http://git-master/r/360088
(cherry picked from commit 9555fa8aef8a773de4a0b25ac880e4a95593c0ef)

Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Change-Id: I6b1a92c85a8fdbed58ff86ff929db8a689a5ceca
Reviewed-on: http://git-master/r/362841