usb: gadget: xudc: fix unused function build issue
Fix below compilation issue pointed out by clang

tegra_xudc.c:284:1: error: unused function 'ep_ctx_read_devaddr'

bug 1745660

Change-Id: I5b4783c48fa3752713f85d62479ac3fa6f8909a4
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1152614
(cherry picked from commit ae177141ecc8b9953acca521663a961c244ca377)
Reviewed-on: http://git-master/r/1159923
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>