platform: nvadsp: fix unused function build issue
Fix following compilation issue pointed by clang

nvadsp/os.c:393:20: error: unused function 'dump_global_symbol_table'

bug 1745660

Change-Id: I69905d821cf3f9859c643dfeaba140b6026f0b22
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1152617
(cherry picked from commit 90cf1aa99354e30ba2ca4ed836dd469a79d37157)
Reviewed-on: http://git-master/r/1159924
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>