i2c: core: fix unused function build issue
Fix the following issue found by clang

i2c-core.c:1221:28: error: unused function 'i2c_adapter_depth'

bug 1745660

Change-Id: Ibbd99142f6ed691a471d9905135d8d7cfee2e1e9
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1152619
(cherry picked from commit e6c0c15478bcaf003a6d4631d4797bf6d5edd337)
Reviewed-on: http://git-master/r/1159925
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>