clk: tegra: add ifdef for tegra_dfll_pwm_output_*
The pwm-tegra-dfll driver could be selected as a loadable
module while this clk-dfll driver can only be built-in.
So there are errors when building the kernel:

 drivers/built-in.o: In function `_dfll_unlock':
 drivers/clk/tegra/clk-dfll.c:1981: undefined reference to `tegra_dfll_pwm_output_disable'
 drivers/built-in.o: In function `_dfll_lock':
 drivers/clk/tegra/clk-dfll.c:1926: undefined reference to `tegra_dfll_pwm_output_enable'

Since the clk-dfll driver can only be =y, it can not call
functions where the driver is =m. So this patch just adds
ifdef for those two function calls.

Bug 1887171

Change-Id: Ie833fa12aaa272ac5cfc339b8109fb5c39916f6d
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: http://git-master/r/1462640
Reviewed-by: svccoveritychecker <svccoveritychecker@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Laxman Dewangan <ldewangan@nvidia.com>
Reviewed-by: Aleksandr Frid <afrid@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
(cherry picked from commit 8fe77f3d38673b65e2a181d4f7c34d04af85452c)