media: platform: tegra: remove of_node_put call
when booting device with OF_DYNAMIC config enabled
observed kernel warning due to of_node_put and then
crash/hang observed.

ERROR: Bad of_node_put() on /host1x/vi@15700000/ports/port@0/endpoint
[    4.051287] [<ffffffc000792b84>] of_node_put+0x14/0x1c
[    4.056423] [<ffffffc0006dd19c>] tegra_vi_graph_parse_one+0x68/0x1b0
[    4.062772] [<ffffffc0006ddab4>] tegra_vi_graph_init+0x20/0x170
[    4.068691] [<ffffffc0006dbd14>] tegra_vi_media_controller_init+0xa4/0x11c

Bug 200207333

Change-Id: I426df2781713ae952fa86bd0033e81892f9bc07a
Signed-off-by: Venkat Reddy Talla <vreddytalla@nvidia.com>
Reviewed-on: http://git-master/r/1175449
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bhanu Murthy V <bmurthyv@nvidia.com>
Reviewed-by: Laxman Dewangan <ldewangan@nvidia.com>