clk: include fs header file in clk driver
when CONFIG_IRQSOFF_TRACER config removed from t186_android_defconfig
observed build errors in clk module, adding fs header file in clk driver
to resolve below compilation errors.

/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:316:8:
error: dereferencing pointer to incomplete type
    inode->i_private);
        ^
/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:320:2:
error: unknown field 'open' specified in initializer
   .open           = freq_stats_table_open,
   ^
/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:321:2:
error: unknown field 'read' specified in initializer
   .read           = seq_read,
   ^
/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:322:2:
error: unknown field 'llseek' specified in initializer
   .llseek         = seq_lseek,
   ^
/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:323:2:
error: unknown field 'release' specified in initializer
 .release        = seq_release,
  ^
/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:628:20:
error: expected ')' before string constant
    freq_stats_set, "%llu\n");

/dvs/git/dirty/git-master_modular/kernel/kernel-4.4/drivers/clk/clk.c:2740:27:
 error: 'freq_stats_fops' undeclared (first use in this function)

Bug  200274003

Change-Id: I8bd9314a70740805f02fd05eeef21ecd9592464f
Signed-off-by: Venkat Reddy Talla <vreddytalla@nvidia.com>
Reviewed-on: http://git-master/r/1303783
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>