driver: correct usb depends for tegra-baseband and MHI
Those two module build is depends on the symbol on CONFIG_USB
and CONFIG_USB_NET, but not declared them in Kconfig and will cause link failure when CONFIG_USB is not enabled.

Error log:
drivers/built-in.o: In function `mdm_init':
kernel/drivers/misc/tegra-baseband/tegra_usb_modem_power.c:861: undefined reference to `usb_register_notify'
drivers/built-in.o: In function `device_add_handler':
kernel/drivers/misc/tegra-baseband/tegra_usb_modem_power.c:283: undefined reference to `usb_ifnum_to_if'
/media/NVIDIA/jasozhang/proj/android-kernel-rebases/kernel/drivers/misc/tegra-baseband/tegra_usb_modem_po
wer.c:293: undefined reference to `usb_match_id'
kernel/drivers/misc/tegra-bseband/tegra_usb_modem_po
wer.c:321: undefined reference to `usb_enable_autosuspend'
drivers/built-in.o: In function `tegra_usb_modem_wake_thread':
kernel/drivers/misc/tegra-baseband/tegra_usb_modem_power.c:203: undefined reference to `usb_autopm_get_interface'
kernel/drivers/misc/tegra-baseband/tegra_usb_modem_power.c:204: undefined reference to`usb_autopm_put_interface_async'
drivers/built-in.o: In function `mhi_net_device_open':
kernel/drivers/net/mhi/mhi_net_device.c:269: undefined reference to `usbnet_pause_rx'
drivers/built-in.o: In function `mhi_device_notify':
kernel/drivers/net/mhi/mhi_net_device.c:289: undefined reference to `usbnet_resume_rx'
drivers/built-in.o: In function `tegra_usb_modem_remove':
kernel/drivers/misc/tegra-baseband/tegra_usb_modem_power.c:936: undefined reference to `usb_unregister_notify'
make[1]: *** [vmlinux] Error 1
make: *** [sub-make] Error 2

Change-Id: I3d227f27b6bbac8e67c1c9bd33970ee765c64bc7
Signed-off-by: Jiejing Zhang <jasozhang@nvidia.com>
Reviewed-on: http://git-master/r/277310
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Tested-by: Bharat Nihalani <bnihalani@nvidia.com>